version: "3.5"
services:
  app-service:
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "7500:7500"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine3.17
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

